### PR TITLE
Added Akkadian language

### PR DESCRIPTION
**Pull request by wincentbalin**
This fixes issue #98.

### CODE REVIEW

**Comment by wincentbalin** [comment]
Also, I would merge the pull request #89 (including the last two commits, of course), as the crash after selecting multiple languages is really annoying.

**Comment by wincentbalin** [comment]
Dear @SubhamTyagi, would you like to review this pull request?

**Comment by wincentbalin** [comment]
Dear @SubhamTyagi , I asked you about reviewing/merging this pull request. Would you like to do that?

**Comment by wincentbalin** [comment]
Dear @SubhamTyagi , would you like to review this pull request?

**Comment by SubhamTyagi** [comment]
Thanks @wincentbalin

**Pull request merged**
