### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by h4n23s**
Hi, 

this PR aims to improve overall design and usability.
 
A ``BottomSheetDialogFragment`` is used to show the resulting text (which can also be shared with other apps now) and a ``SwipeRefreshLayout`` replaces the ``refresh`` icon which is currently in the menu bar. When clicking on the ``FloatingActionButton`` in the bottom right corner the file chooser appears.

I did include a few animations which, in my opinion, make the app look much smoother. 🙂

<div>

</div>

### CODE REVIEW

**Comment by h4n23s** [comment]
Would you mind if I were to [add support](https://developer.android.com/studio/write/java8-support) for Java 8?

**Comment by SubhamTyagi** [comment]
Could you provide the Apk file.

**Comment by SubhamTyagi** [comment]
> 
> 
> Would you mind if I were to [add support](https://developer.android.com/studio/write/java8-support) for Java 8?

👍

**Comment by h4n23s** [comment]
> 
> 
> Could you provide the Apk file.

Sure. For which architecture should I build the APK?

**Comment by SubhamTyagi** [comment]
> 
> 
> > Could you provide the Apk file.
> 
> Sure. For which architecture should I build the APK?

"arm64-v8a"

**Comment by h4n23s** [comment]
> 
> 
> > > Could you provide the Apk file.
> > 
> > 
> > Sure. For which architecture should I build the APK?
> 
> "arm64-v8a"

Here you go 🙂: [app-arm64-v8a-debug.zip](https://github.com/SubhamTyagi/android-ocr/files/5919974/app-arm64-v8a-debug.zip)

**Comment by SubhamTyagi** [comment]
1. How do user open the `BottomSheetDialogFragment` **Result**, if  it is accidentally closed(I made this in first attempt 😄 ) or user want to see the Result again(without doing the OCR again)?

2. Color of Toolbar items should be different from Resultant text.
toolbar

**Comment by h4n23s** [comment]
> How do user open the BottomSheetDialogFragment Result, if it is accidentally closed(I made this in first attempt 😄 ) or user want to see the Result again(without doing the OCR again)?

That's right. I'm currently not sure how to solve this issue while still keeping the design it simple and clean. Any suggestions? 🙂 

> Color of Toolbar items should be different from Resultant text.

What about this?

Screenshot_1612373077

**Comment by SubhamTyagi** [comment]
>That's right. I'm currently not sure how to solve this issue while still keeping the design it simple and clean. Any suggestions? 🙂

Put a History button adjacent to :settings button 

>What about this?

Now this making a difference. Better than old one

**Comment by h4n23s** [comment]
Done! I approached the 'show the last result' option a little bit differently though:

Screenshot_1612378462

**Pull request merged**
